### ISSUE TITLE
Panic during apex deploy

### ISSUE THREAD

**Issue by zen4ever** [apex/apex#334]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x139e99]

goroutine 9 [running]:
panic(0x67b240, 0xc8200120f0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/apex/apex/function.(*Function).configChanged(0xc820081080, 0xc82048a2f0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:660 +0x409
github.com/apex/apex/function.(*Function).Deploy(0xc820081080, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:195 +0x2b6
github.com/apex/apex/project.(*Project).Deploy.func1.1(0xc820064d80, 0xc820081080, 0xc820064de0)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:181 +0x71
created by github.com/apex/apex/project.(*Project).Deploy.func1
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:187 +0xd0
```

**Comment by matthew-andrews** [comment]
I saw this too.  Worked around it by temporarily downgrading to v0.7.0.

**Comment by mthenw** [comment]
Thanks for reporting. It's related to how we handle VPC configuration.

**Comment by tj** [comment]
wtf weirdddd that's the thing I couldn't reproduce..

**Comment by zen4ever** [comment]
yeah, for me I don't think it is related to VPC. I can only reproduce it on one of my projects

**Comment by zen4ever** [comment]
I think for me it is happening after upgrading from apex v0.5.1 to v0.7.1, I had functions deployed with older version, and they are throwing the exception. New function deployments seem to be working fine
