### ISSUE TITLE
Deploy is failing

### ISSUE THREAD

**Issue by mooyoul** [apex/apex#440]
- Operating system
Amazon Linux
  - Version (`apex version`)
0.9.0

First of all, Thanks for providing this awesome program. (Ah, Express, node-debug are also my favorites. thanks TJ!)

I'm having an issue with Deploying my Lambda function using Apex on my EC2 Instance which is installed Amazon Linux.

When first deploy attempt, Apex outputs this error:
```
[ec2-user@ip-172-31-***-*** qna-keyword-classification]$ apex deploy
   • creating function         function=train
   ⨯ Error: function train: RequestError: send request failed
caused by: Post https://lambda.ap-northeast-1.amazonaws.com/2015-03-31/functions: write tcp 172.31.19.107:51536->52.69.23.0:443: write: broken pipe
```

And when second deploy attempt (function name specified), Apex killed with Golang exception:
```
[ec2-user@ip-172-31-***-*** qna-keyword-classification]$ apex deploy train
   • creating function         function=train
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc21aa0, 0x16)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sysMap(0xc84c9b0000, 0x11000000, 0x0, 0xf5bc38)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0xf3f5c0, 0x11000000, 0xc800000000)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0xf3f5c0, 0x8800, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0xf3f5c0, 0x8800, 0x7ff790848ac8)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0xf3f5c0, 0x8800, 0xffffff0100000000, 0xc820035ec8)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820035ee0)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xf3f5c0, 0x8800, 0x10100000000, 0x20)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x10fffc00, 0xc800000001, 0xc820548ae0)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc82001a000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 9 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820548978 sp=0xc820548970
runtime.mallocgc(0x10fffc00, 0x98b500, 0xc800000001, 0xc8441b0000)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc820548a50 sp=0xc820548978
runtime.newarray(0x98b500, 0x10fffc00, 0xc820548af0)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc820548a90 sp=0xc820548a50
runtime.makeslice(0x978420, 0x10fffc00, 0x10fffc00, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc820548ae0 sp=0xc820548a90
bytes.makeSlice(0x10fffc00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:198 +0x64 fp=0xc820548b30 sp=0xc820548ae0
bytes.(*Buffer).grow(0xc8201276c0, 0x400, 0x400)
	/usr/local/go/src/bytes/buffer.go:106 +0x282 fp=0xc820548bd8 sp=0xc820548b30
bytes.(*Buffer).Write(0xc8201276c0, 0xc8205c76b8, 0x400, 0x400, 0xc8427afa00, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:134 +0x4b fp=0xc820548c30 sp=0xc820548bd8
encoding/base64.(*encoder).Write(0xc8205c7680, 0xc8427afa00, 0x6cbd7e, 0x1a00400, 0x65ffa00, 0x0, 0x0)
	/usr/local/go/src/encoding/base64/base64.go:188 +0x470 fp=0xc820548cc8 sp=0xc820548c30
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildScalar(0x978420, 0xc8205cc7c8, 0x197, 0xc8201276c0, 0xbb7010, 0xb, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:210 +0x748 fp=0xc820548ed0 sp=0xc820548cc8
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildAny(0x978420, 0xc8205cc7c8, 0x197, 0xc8201276c0, 0xbb7010, 0xb, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:64 +0x4a7 fp=0xc820549020 sp=0xc820548ed0
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildStruct(0xb35680, 0xc8205cc7b0, 0x199, 0xc8201276c0, 0xc23440, 0x10, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:126 +0x750 fp=0xc8205492c0 sp=0xc820549020
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildAny(0xb35680, 0xc8205cc7b0, 0x199, 0xc8201276c0, 0xc23440, 0x10, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:58 +0x433 fp=0xc820549410 sp=0xc8205492c0
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildStruct(0xb54e60, 0xc8205c5360, 0x199, 0xc8201276c0, 0xc23440, 0x10, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:126 +0x750 fp=0xc8205496b0 sp=0xc820549410
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.buildAny(0xb54e60, 0xc8205c5360, 0x199, 0xc8201276c0, 0xc23440, 0x10, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:58 +0x433 fp=0xc820549800 sp=0xc8205496b0
github.com/aws/aws-sdk-go/private/protocol/json/jsonutil.BuildJSON(0xaeabc0, 0xc8205c5360, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go:23 +0xb9 fp=0xc820549868 sp=0xc820549800
github.com/aws/aws-sdk-go/private/protocol/jsonrpc.Build(0xc8205cea80)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go:38 +0x9b fp=0xc8205499c8 sp=0xc820549868
github.com/aws/aws-sdk-go/private/protocol/restjson.Build(0xc8205cea80)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go:36 +0xaa fp=0xc820549a08 sp=0xc8205499c8
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8205ceba8, 0xc8205cea80)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0xc3 fp=0xc820549ad0 sp=0xc820549a08
github.com/aws/aws-sdk-go/aws/request.(*Request).Build(0xc8205cea80, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/aws/request/request.go:194 +0x10a fp=0xc820549b08 sp=0xc820549ad0
github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc8205cea80, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/aws/request/request.go:210 +0x31 fp=0xc820549b40 sp=0xc820549b08
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8205cea80, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/aws/request/request.go:258 +0x703 fp=0xc820549ce0 sp=0xc820549b40
github.com/aws/aws-sdk-go/service/lambda.(*Lambda).CreateFunction(0xc820026140, 0xc8205c5360, 0x0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/aws/aws-sdk-go/service/lambda/api.go:170 +0x4f fp=0xc820549d10 sp=0xc820549ce0
github.com/apex/apex/function.(*Function).Create(0xc820069340, 0xc83c1b0000, 0x6ccb77e, 0x7fffe00, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:338 +0x476 fp=0xc820549e20 sp=0xc820549d10
github.com/apex/apex/function.(*Function).Deploy(0xc820069340, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/function/function.go:190 +0x24c fp=0xc820549ee0 sp=0xc820549e20
github.com/apex/apex/project.(*Project).Deploy.func1.1(0xc82004cf60, 0xc820069340, 0xc82004cfc0)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:189 +0x71 fp=0xc820549f88 sp=0xc820549ee0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820549f90 sp=0xc820549f88
created by github.com/apex/apex/project.(*Project).Deploy.func1
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:195 +0xd0

goroutine 1 [chan receive, 2 minutes]:
github.com/apex/apex/project.(*Project).Deploy(0xc8201561a0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:202 +0x20c
github.com/apex/apex/project.(*Project).DeployAndClean(0xc8201561a0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:167 +0x2d
github.com/apex/apex/cmd/apex/deploy.run(0xf34460, 0xc820144750, 0x1, 0x1, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/apex/cmd/apex/deploy/deploy.go:92 +0x808
github.com/spf13/cobra.(*Command).execute(0xf34460, 0xc820144710, 0x1, 0x1, 0x0, 0x0)
	/Users/tj/dev/src/github.com/spf13/cobra/command.go:561 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0xf35660, 0xf34460, 0x0, 0x0)
	/Users/tj/dev/src/github.com/spf13/cobra/command.go:651 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xf35660, 0x0, 0x0)
	/Users/tj/dev/src/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/Users/tj/dev/src/github.com/apex/apex/cmd/apex/main.go:84 +0x6af

goroutine 8 [chan send, 2 minutes]:
github.com/tj/go-sync/semaphore.Semaphore.Wait(0xc82004cf60)
	/Users/tj/dev/src/github.com/tj/go-sync/semaphore/semaphore.go:20 +0x53
github.com/apex/apex/project.(*Project).Deploy.func1(0xc8201561a0, 0xc82004cf60, 0xc82004cfc0)
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:198 +0xfd
created by github.com/apex/apex/project.(*Project).Deploy
	/Users/tj/dev/src/github.com/apex/apex/project/project.go:200 +0x1d2

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7ff79084dc90, 0x72, 0xc820029c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820042c30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820042c30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820042bd0, 0xc820029c00, 0x400, 0x400, 0x0, 0x7ff790b68050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200260b0, 0xc820029c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82180e060, 0x7ff79084e048, 0xc8200260b0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820148000, 0xcd8017, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820148000, 0xc820132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7ff79084ea40, 0xc820148000, 0xc8214eeaf8, 0xc820132000, 0x1000, 0x1000, 0x404a23, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8205cb500, 0xc820132000, 0x1000, 0x1000, 0xc820039d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8201fe180)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201fe180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8214eea90)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc8214eea90)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb
```

I don't know why it is failing. and can`t guess where OOM was occurred.

**Comment by mooyoul** [comment]
Gotcha. I just noticed my build was exceed size limitation (50MByte) on debug log output.

```
   • created build (114 MB)    function=train <=============== OOPS!
   • fetching config           function=train
   • creating function         function=train
   ⨯ Error: function train: RequestError: send request failed
caused by: Post https://lambda.ap-northeast-1.amazonaws.com/2015-03-31/functions: write tcp 172.31.***.***:46614->52.69.25.229:443: write: broken pipe
```

The main problem was node_module was too big.
I'm trying to reduce size of node_modules by upgrading NPM v3 which has changed dependency tree.

**Comment by mooyoul** [comment]
Okay, It seems working now.
Anyway, i think there are two issues.

1) There are no warnings/errors on build when built zip archive exceeds 50Mbytes which is Lambda limitation.
2) Archiving *huge* zip archive may lead to OOM on tiny machines (which has low memor. e.g. Archiving 150MB+ files on 1GB RAM)

**Comment by tj** [comment]
Ahh yep the zip is built in memory, might have to use `--concurrency 1` for cases like that. I don't think I've gone beyond ~25 with mine yet, I'll look into getting a better error message for that

**Comment by mooyoul** [comment]
Oops. i didn't know that `concurrency` option exists. Maybe isn`t it not documented?

Anyway i'd prefer archive in memory too. it is really fast.
I'll take look about webpack or browserify with Lambda, but some dependencies require node-gyp to build their native addon module :( I hope webpack or browserify plays well with these dependencies. thanks for your guide!

**Comment by tj** [comment]
Yep it's documented in the `apex help deploy` output:

```
  -c, --concurrency int   Concurrent deploys (default 5)
```

Not a whole lot we can do memory-wise other than a lower default concurrency (might make sense). Closing for now but if others have the same issue it might make more sense to lower.
