### ISSUE TITLE
PSA - macOS Sierra upgrade requirements

### ISSUE THREAD

**Issue by ryantuck** [apex/apex#551]
I recently upgraded to macOS Sierra.

I attempted to `apex deploy my_function` as normal and got some gnarly looking error output. 

After `apex upgrade` to v0.10.3, had the same issue.

I assumed I might need to upgrade `go`, which I do via `brew upgrade go`. To do so I needed to upgrade XCode to v8.0, which took every bit of a half hour on a decent internet connection.

After upgrading XCode, `apex deploy` worked as expected.

I guess this is both an issue and a fix for the issue, but wanted to at least share in case others ran into the same problem!

**Comment by DavidTPate** [comment]
Thanks for sharing @ryantuck it's probably something that would be good to mention in the documentation I'm thinking.

**Comment by tj** [comment]
Should be ok in here even, not sure about most people but I usually go straight to a repo and search issues

**Comment by ryantuck** [comment]
errr actually it's still not working as expected.

Here's my system:

```
🔥  apex version
Apex version 0.10.3
🔥  go version
go version go1.7.1 darwin/amd64
🔥  sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A320
```

it's sporadically either hanging, deploying, or erroring out with output that looks like this:

```
🔥 apex deploy util-ftp-s3
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xf3c6758 pc=0x913e5]

runtime stack:
runtime.throw(0x978800, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0x70000f340cc0 sp=0x70000f340ca8
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000f340d10 sp=0x70000f340cc0
runtime/internal/atomic.Load64(0xf3c6758, 0xf3c675e0480)
        /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000f340d18 sp=0x70000f340d10
runtime.lfstackpop(0xca5828, 0x219b3)
        /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0x70000f340d50 sp=0x70000f340d18
runtime.getempty(0x67, 0x0)
        /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0x70000f340d80 sp=0x70000f340d50
runtime.(*gcWork).init(0x70000f340e38)
        /usr/local/go/src/runtime/mgcwork.go:100 +0x53 fp=0x70000f340d98 sp=0x70000f340d80
runtime.(*gcWork).get(0x70000f340e38, 0x1)
        /usr/local/go/src/runtime/mgcwork.go:172 +0x38 fp=0x70000f340dc8 sp=0x70000f340d98
runtime.gcDrain(0x70000f340e38, 0x0)
        /usr/local/go/src/runtime/mgcmark.go:831 +0x122 fp=0x70000f340e00 sp=0x70000f340dc8
runtime.gcMark(0xaf29c4300)
        /usr/local/go/src/runtime/mgc.go:1560 +0xf9 fp=0x70000f340e60 sp=0x70000f340e00
runtime.gcMarkTermination.func1()
        /usr/local/go/src/runtime/mgc.go:1174 +0x23 fp=0x70000f340e70 sp=0x70000f340e60
runtime.systemstack(0xc820022000)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79 fp=0x70000f340e78 sp=0x70000f340e70
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1051 fp=0x70000f340e80 sp=0x70000f340e78

goroutine 11 [garbage collection]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820026510 sp=0xc820026508
runtime.gcMarkTermination()
        /usr/local/go/src/runtime/mgc.go:1182 +0x136 fp=0xc820026720 sp=0xc820026510
runtime.gcMarkDone()
        /usr/local/go/src/runtime/mgc.go:1146 +0x29e fp=0xc820026740 sp=0xc820026720
runtime.gcBgMarkWorker(0xc82001f500)
        /usr/local/go/src/runtime/mgc.go:1480 +0x488 fp=0xc8200267b8 sp=0xc820026740
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200267c0 sp=0xc8200267b8
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1330 +0x92

goroutine 1 [chan receive]:
runtime.gopark(0x9e3348, 0xc820017138, 0x88c280, 0xc, 0x17, 0x3)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc8200597c0 sp=0xc820059798
runtime.goparkunlock(0xc820017138, 0x88c280, 0xc, 0x900417, 0x3)
        /usr/local/go/src/runtime/proc.go:268 +0x54 fp=0xc8200597f8 sp=0xc8200597c0
runtime.chanrecv(0x5f6000, 0xc8200170e0, 0xc820059920, 0xc820141801, 0xe0000)
        /usr/local/go/src/runtime/chan.go:470 +0x49f fp=0xc820059880 sp=0xc8200597f8
runtime.chanrecv2(0x5f6000, 0xc8200170e0, 0xc820059920, 0xc820017080)
        /usr/local/go/src/runtime/chan.go:360 +0x2b fp=0xc8200598b0 sp=0xc820059880
github.com/apex/apex/project.(*Project).Deploy(0xc82016c4e0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:216 +0x20c fp=0xc820059960 sp=0xc8200598b0
github.com/apex/apex/project.(*Project).DeployAndClean(0xc82016c4e0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:181 +0x2d fp=0xc820059990 sp=0xc820059960
github.com/apex/apex/cmd/apex/deploy.run(0xc9fac0, 0xc82014e770, 0x1, 0x1, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/cmd/apex/deploy/deploy.go:102 +0xa41 fp=0xc820059b50 sp=0xc820059990
github.com/tj/cobra.(*Command).execute(0xc9fac0, 0xc82014e730, 0x1, 0x1, 0x0, 0x0)
        /Users/tj/dev/src/github.com/tj/cobra/command.go:573 +0x668 fp=0xc820059c68 sp=0xc820059b50
github.com/tj/cobra.(*Command).ExecuteC(0xca0de0, 0xc9fac0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/tj/cobra/command.go:663 +0x55c fp=0xc820059d78 sp=0xc820059c68
github.com/tj/cobra.(*Command).Execute(0xca0de0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/tj/cobra/command.go:622 +0x2d fp=0xc820059da0 sp=0xc820059d78
main.main()
        /Users/tj/dev/src/github.com/apex/apex/cmd/apex/main.go:101 +0x67a fp=0xc820059f50 sp=0xc820059da0
runtime.main()
        /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820059fa0 sp=0xc820059f50
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820059fa8 sp=0xc820059fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003efb8 sp=0xc82003efb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x9e3348, 0xca5060, 0x88e4a0, 0xf, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82002a758 sp=0xc82002a730
runtime.goparkunlock(0xca5060, 0x88e4a0, 0xf, 0xc820000114, 0x1)
        /usr/local/go/src/runtime/proc.go:268 +0x54 fp=0xc82002a790 sp=0xc82002a758
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:229 +0xb8 fp=0xc82002a7c0 sp=0xc82002a790
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002a7c8 sp=0xc82002a7c0
created by runtime.init.4
        /usr/local/go/src/runtime/proc.go:218 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x9e3348, 0xca5200, 0x883450, 0xd, 0x51d14, 0x1)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82002af48 sp=0xc82002af20
runtime.goparkunlock(0xca5200, 0x883450, 0xd, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:268 +0x54 fp=0xc82002af80 sp=0xc82002af48
runtime.bgsweep(0xc82001c070)
        /usr/local/go/src/runtime/mgcsweep.go:79 +0x14d fp=0xc82002afb8 sp=0xc82002af80
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002afc0 sp=0xc82002afb8
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:191 +0x53

goroutine 4 [finalizer wait]:
runtime.gopark(0x9e3348, 0xcc2810, 0x88df60, 0xe, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82002b718 sp=0xc82002b6f0
runtime.goparkunlock(0xcc2810, 0x88df60, 0xe, 0x2000000014, 0x1)
        /usr/local/go/src/runtime/proc.go:268 +0x54 fp=0xc82002b750 sp=0xc82002b718
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:158 +0xaa fp=0xc82002b7c0 sp=0xc82002b750
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002b7c8 sp=0xc82002b7c0
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:139 +0x60

goroutine 8 [chan send]:
runtime.gopark(0x9e3348, 0xc8200170d8, 0x88c290, 0x9, 0x16, 0x3)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82002d620 sp=0xc82002d5f8
runtime.goparkunlock(0xc8200170d8, 0x88c290, 0x9, 0xc820001b16, 0x3)
        /usr/local/go/src/runtime/proc.go:268 +0x54 fp=0xc82002d658 sp=0xc82002d620
runtime.chansend(0x7cdf60, 0xc820017080, 0xc82002d730, 0xc82002d701, 0x2f2ec3, 0xc82002d701)
        /usr/local/go/src/runtime/chan.go:213 +0x449 fp=0xc82002d6e0 sp=0xc82002d658
runtime.chansend1(0x7cdf60, 0xc820017080, 0xc82002d730)
        /usr/local/go/src/runtime/chan.go:100 +0x43 fp=0xc82002d718 sp=0xc82002d6e0
github.com/tj/go-sync/semaphore.Semaphore.Wait(0xc820017080)
        /Users/tj/dev/src/github.com/tj/go-sync/semaphore/semaphore.go:20 +0x53 fp=0xc82002d740 sp=0xc82002d718
github.com/apex/apex/project.(*Project).Deploy.func1(0xc82016c4e0, 0xc820017080, 0xc8200170e0)
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:212 +0xfd fp=0xc82002d7a8 sp=0xc82002d740
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002d7b0 sp=0xc82002d7a8
created by github.com/apex/apex/project.(*Project).Deploy
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:214 +0x1d2

goroutine 9 [runnable]:
runtime.makeslice(0x5f3c60, 0x0, 0x13, 0xc8204e0230, 0x13, 0x13)
        /usr/local/go/src/runtime/slice.go:18 fp=0xc82025d0a8 sp=0xc82025d0a0
regexp.progMachine(0xc820106360, 0x0, 0x0)
        /usr/local/go/src/regexp/exec.go:76 +0x231 fp=0xc82025d170 sp=0xc82025d0a8
regexp.(*Regexp).get(0xc8204e21e0, 0xc8204e21e0)
        /usr/local/go/src/regexp/regexp.go:211 +0x107 fp=0xc82025d1b8 sp=0xc82025d170
regexp.(*Regexp).doExecute(0xc8204e21e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820208296, 0x1b, 0x0, 0x0, ...)
        /usr/local/go/src/regexp/exec.go:428 +0x4d fp=0xc82025d318 sp=0xc82025d1b8
regexp.(*Regexp).MatchString(0xc8204e21e0, 0xc820208296, 0x1b, 0x0)
        /usr/local/go/src/regexp/regexp.go:411 +0x67 fp=0xc82025d388 sp=0xc82025d318
regexp.MatchString(0xc8201ae140, 0x16, 0xc820208296, 0x1b, 0xc82014e840, 0x0, 0x0)
        /usr/local/go/src/regexp/regexp.go:438 +0x83 fp=0xc82025d3b8 sp=0xc82025d388
github.com/rliebling/gitignorer.GitIgnore(0xe58470, 0xc820106330, 0xc820208296, 0x1b, 0xc820208200, 0x0, 0x0)
        /Users/tj/dev/src/github.com/rliebling/gitignorer/gitignore.go:89 +0x1c0 fp=0xc82025d518 sp=0xc82025d3b8
github.com/apex/apex/utils.LoadFiles.func1(0xc820208280, 0x31, 0xe58a28, 0xc82017c270, 0x0, 0x0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/utils/utils.go:44 +0x235 fp=0xc82025d5d0 sp=0xc82025d518
path/filepath.walk(0xc820208280, 0x31, 0xe58a28, 0xc82017c270, 0xc820013bc0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:349 +0x80 fp=0xc82025d708 sp=0xc82025d5d0
path/filepath.walk(0xc82026fb30, 0x23, 0xe58a28, 0xc8200632b0, 0xc820013bc0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82025d840 sp=0xc82025d708
path/filepath.walk(0xc8200bbf80, 0x1d, 0xe58a28, 0xc820062680, 0xc820013bc0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82025d978 sp=0xc82025d840
path/filepath.walk(0xc8201634a0, 0x15, 0xe58a28, 0xc82017c340, 0xc820013bc0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc82025dab0 sp=0xc82025d978
path/filepath.Walk(0xc8201634a0, 0x15, 0xc820013bc0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc82025db18 sp=0xc82025dab0
github.com/apex/apex/utils.LoadFiles(0xc8201634a0, 0x15, 0xc820162d20, 0x1b, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/utils/utils.go:56 +0xfa fp=0xc82025db58 sp=0xc82025db18
github.com/apex/apex/function.(*Function).Build(0xc82007f340, 0x0, 0x0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/function/function.go:589 +0x1cd fp=0xc82025dd50 sp=0xc82025db58
github.com/apex/apex/function.(*Function).BuildBytes(0xc82007f340, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/function/function.go:564 +0x5c fp=0xc82025de10 sp=0xc82025dd50
github.com/apex/apex/function.(*Function).Deploy(0xc82007f340, 0x0, 0x0)
        /Users/tj/dev/src/github.com/apex/apex/function/function.go:228 +0x8b fp=0xc82025ded0 sp=0xc82025de10
github.com/apex/apex/project.(*Project).Deploy.func1.1(0xc820017080, 0xc82007f340, 0xc8200170e0)
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:203 +0x71 fp=0xc82025df78 sp=0xc82025ded0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82025df80 sp=0xc82025df78
created by github.com/apex/apex/project.(*Project).Deploy.func1
        /Users/tj/dev/src/github.com/apex/apex/project/project.go:209 +0xd0

goroutine 10 [GC worker (idle)]:
runtime.gopark(0xc82014e1b0, 0xc82002dfa0, 0x8f5a00, 0x10, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82002df40 sp=0xc82002df18
runtime.gcBgMarkWorker(0xc82001e000)
        /usr/local/go/src/runtime/mgc.go:1403 +0xda fp=0xc82002dfb8 sp=0xc82002df40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002dfc0 sp=0xc82002dfb8
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1330 +0x92

goroutine 12 [GC worker (idle)]:
runtime.gopark(0xc82051c008, 0xc820026fa0, 0x8f5a00, 0x10, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc820026f40 sp=0xc820026f18
runtime.gcBgMarkWorker(0xc820020a00)
        /usr/local/go/src/runtime/mgc.go:1403 +0xda fp=0xc820026fb8 sp=0xc820026f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820026fc0 sp=0xc820026fb8
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1330 +0x92

goroutine 13 [GC worker (idle)]:
runtime.gopark(0xc8202dc000, 0xc8200277a0, 0x8f5a00, 0x10, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc820027740 sp=0xc820027718
runtime.gcBgMarkWorker(0xc820022000)
        /usr/local/go/src/runtime/mgc.go:1403 +0xda fp=0xc8200277b8 sp=0xc820027740
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200277c0 sp=0xc8200277b8
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1330 +0x92
[signal 0xb code=0x1 addr=0xf3c6758 pc=0x913e5]

runtime stack:
runtime.throw(0x978800, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0x7fff5fbff518 sp=0x7fff5fbff500
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7fff5fbff568 sp=0x7fff5fbff518
runtime/internal/atomic.Load64(0xf3c6758, 0xf3c675e0480)
        /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x7fff5fbff570 sp=0x7fff5fbff568
runtime.lfstackpop(0xca5828, 0x0)
        /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0x7fff5fbff5a8 sp=0x7fff5fbff570
runtime.getempty(0x65, 0x0)
        /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0x7fff5fbff5d8 sp=0x7fff5fbff5a8
runtime.(*gcWork).init(0x7fff5fbff678)
        /usr/local/go/src/runtime/mgcwork.go:97 +0x20 fp=0x7fff5fbff5f0 sp=0x7fff5fbff5d8
runtime.(*gcWork).get(0x7fff5fbff678, 0x7fff00000001)
        /usr/local/go/src/runtime/mgcwork.go:172 +0x38 fp=0x7fff5fbff620 sp=0x7fff5fbff5f0
runtime.gcDrain(0x7fff5fbff678, 0x0)
        /usr/local/go/src/runtime/mgcmark.go:831 +0x122 fp=0x7fff5fbff658 sp=0x7fff5fbff620
runtime.gchelper()
        /usr/local/go/src/runtime/mgc.go:1806 +0x7e fp=0x7fff5fbff6a8 sp=0x7fff5fbff658
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1541 +0x13f fp=0x7fff5fbff6c8 sp=0x7fff5fbff6a8
runtime.findrunnable(0xc820020a00, 0x0)
        /usr/local/go/src/runtime/proc.go:1976 +0x739 fp=0x7fff5fbff748 sp=0x7fff5fbff6c8
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2075 +0x24f fp=0x7fff5fbff780 sp=0x7fff5fbff748
runtime.park_m(0xc820448180)
        /usr/local/go/src/runtime/proc.go:2140 +0x18b fp=0x7fff5fbff7a8 sp=0x7fff5fbff780
runtime.mcall(0x7fff5fbff7d0)
        /usr/local/go/src/runtime/asm_amd64.s:233 +0x5b fp=0x7fff5fbff7b8 sp=0x7fff5fbff7a8
[signal 0xb code=0x1 addr=0xf3c6758 pc=0x913e5]

runtime stack:
runtime.throw(0x978800, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0x70000f2bdbe0 sp=0x70000f2bdbc8
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000f2bdc30 sp=0x70000f2bdbe0
runtime/internal/atomic.Load64(0xf3c6758, 0xf3c675e0480)
        /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000f2bdc38 sp=0x70000f2bdc30
runtime.lfstackpop(0xca5828, 0x5adbb)
        /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0x70000f2bdc70 sp=0x70000f2bdc38
runtime.getempty(0x65, 0x0)
        /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0x70000f2bdca0 sp=0x70000f2bdc70
runtime.(*gcWork).init(0x70000f2bdd40)
        /usr/local/go/src/runtime/mgcwork.go:97 +0x20 fp=0x70000f2bdcb8 sp=0x70000f2bdca0
runtime.(*gcWork).get(0x70000f2bdd40, 0x700000000001)
        /usr/local/go/src/runtime/mgcwork.go:172 +0x38 fp=0x70000f2bdce8 sp=0x70000f2bdcb8
runtime.gcDrain(0x70000f2bdd40, 0x0)
        /usr/local/go/src/runtime/mgcmark.go:831 +0x122 fp=0x70000f2bdd20 sp=0x70000f2bdce8
runtime.gchelper()
        /usr/local/go/src/runtime/mgc.go:1806 +0x7e fp=0x70000f2bdd70 sp=0x70000f2bdd20
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1541 +0x13f fp=0x70000f2bdd90 sp=0x70000f2bdd70
runtime.findrunnable(0xc820022000, 0x0)
        /usr/local/go/src/runtime/proc.go:1976 +0x739 fp=0x70000f2bde10 sp=0x70000f2bdd90
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2075 +0x24f fp=0x70000f2bde48 sp=0x70000f2bde10
runtime.park_m(0xc820448300)
        /usr/local/go/src/runtime/proc.go:2140 +0x18b fp=0x70000f2bde70 sp=0x70000f2bde48
runtime.mcall(0xdd3000)
        /usr/local/go/src/runtime/asm_amd64.s:233 +0x5b fp=0x70000f2bde80 sp=0x70000f2bde70
[signal 0xb code=0x1 addr=0xf3c6758 pc=0x913e5]

runtime stack:
runtime.throw(0x978800, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0x70000f1b7ac8 sp=0x70000f1b7ab0
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x70000f1b7b18 sp=0x70000f1b7ac8
runtime/internal/atomic.Load64(0xf3c6758, 0xf3c675e0480)
        /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0x70000f1b7b20 sp=0x70000f1b7b18
runtime.lfstackpop(0xca5828, 0x0)
        /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0x70000f1b7b58 sp=0x70000f1b7b20
runtime.getempty(0x65, 0x0)
        /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0x70000f1b7b88 sp=0x70000f1b7b58
runtime.(*gcWork).init(0x70000f1b7c28)
        /usr/local/go/src/runtime/mgcwork.go:97 +0x20 fp=0x70000f1b7ba0 sp=0x70000f1b7b88
runtime.(*gcWork).get(0x70000f1b7c28, 0x700000000001)
        /usr/local/go/src/runtime/mgcwork.go:172 +0x38 fp=0x70000f1b7bd0 sp=0x70000f1b7ba0
runtime.gcDrain(0x70000f1b7c28, 0x0)
        /usr/local/go/src/runtime/mgcmark.go:831 +0x122 fp=0x70000f1b7c08 sp=0x70000f1b7bd0
runtime.gchelper()
        /usr/local/go/src/runtime/mgc.go:1806 +0x7e fp=0x70000f1b7c58 sp=0x70000f1b7c08
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1541 +0x13f fp=0x70000f1b7c78 sp=0x70000f1b7c58
runtime.gcstopm()
        /usr/local/go/src/runtime/proc.go:1742 +0x128 fp=0x70000f1b7ca8 sp=0x70000f1b7c78
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2039 +0x9c fp=0x70000f1b7ce0 sp=0x70000f1b7ca8
runtime.goschedImpl(0xc820001c80)
        /usr/local/go/src/runtime/proc.go:2155 +0x134 fp=0x70000f1b7cf8 sp=0x70000f1b7ce0
runtime.gopreempt_m(0xc820001c80)
        /usr/local/go/src/runtime/proc.go:2170 +0x32 fp=0x70000f1b7d08 sp=0x70000f1b7cf8
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:932 +0xa8c fp=0x70000f1b7e78 sp=0x70000f1b7d08
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:359 +0x7f fp=0x70000f1b7e80 sp=0x70000f1b7e78
```

**Comment by polds** [comment]
I'm suspecting it's due to the distributed binaries being built with a different version of macOS. Have you tried compiling apex yourself on Sierra? I too was having similar issues, the panic you posted above and Segfaults too.

Also.. sounds crazy but try a build again.. I found it changes from a panic, to a segfault to working.

**Comment by ryantuck** [comment]
can't seem to compile it myself - looks like it's complaining about being `unable to find runtime/cgo.a`. Even setting `CGO_ENABLED=0` doesn't resolve the issue. Got any tips on doing so @polds?

```
🔥  ~/go_stuff/src/github.com/apex/apex 🔥  make
[+] releasing
[+] re-generating
[+] building
Number of parallel builds: 3

-->     linux/amd64: github.com/apex/apex/cmd/apex
-->     linux/ppc64: github.com/apex/apex/cmd/apex
-->       linux/386: github.com/apex/apex/cmd/apex
-->   openbsd/amd64: github.com/apex/apex/cmd/apex
-->   linux/ppc64le: github.com/apex/apex/cmd/apex
-->      darwin/386: github.com/apex/apex/cmd/apex
-->    darwin/amd64: github.com/apex/apex/cmd/apex
-->      darwin/arm: github.com/apex/apex/cmd/apex
-->    darwin/arm64: github.com/apex/apex/cmd/apex
-->     windows/386: github.com/apex/apex/cmd/apex
-->   windows/amd64: github.com/apex/apex/cmd/apex
-->     openbsd/386: github.com/apex/apex/cmd/apex
-->       linux/arm: github.com/apex/apex/cmd/apex
-->     linux/arm64: github.com/apex/apex/cmd/apex

1 errors occurred:
--> darwin/arm64 error: exit status 2
Stderr: # github.com/apex/apex/cmd/apex
warning: unable to find runtime/cgo.a
/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/l8/61sd07y947v050cp246d0r580000gn/T/go-link-460797017/go.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/l8/61sd07y947v050cp246d0r580000gn/T/go-link-460797017/go.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


make[1]: *** [build] Error 1
make: *** [release] Error 2
```

**Comment by ryantuck** [comment]
actually since I ended up generating `apex_darwin_amd64*` via the above process I'm now able to successfully deploy etc via the following:

```
~/go_stuff/src/github/apex/apex/apex_darwin_amd64 deploy my-function
```

so I guess for now I'll just rename it and replace the original `apex` binary - I guess this still seems like a bug though, right?

**Comment by polds** [comment]
As I'm pretty sure it's macOS version related and Sierra is still in preview it's probably not a bug yet until next week when Sierra is released. At that point Apex would probably need to be recompiled and re-released. 

Out of curiosity I'm going to take a Sierra binary and try it on El Capitan and see if it still works, hopefully backwards compatibility hasn't been sacrificed. I'll post back with the results.

**Comment by polds** [comment]
Ok Sierra binaries work fine in El Capitan.

**Comment by Savjee** [comment]
Got the same issue with the final release of macOS Sierra.

**Comment by kopertop** [comment]
I also just started running into this problem. As @ryantuck noted it's not every time, just on some functions that seem to break badly.

I'm going to try building from source as well to get it working at least until a new official version can be released.

**Comment by tj** [comment]
Thanks for investigating @polds! I'll try and update soon and release bins unless another contributor gets to it first, I'm always hesitant to upgrade OSX, for reasons like this haha.

**Comment by kopertop** [comment]
It may also be important to note that this occasionally fails when trying ```apex upgrade``` so existing users may have to end up re-installing from scratch.

Also, I'm not sure if something changed in go, but doing ```go get -u ./...``` in the source directory fails. I'm not a go developer by any means, so I'm sure I'm doing something wrong, but I couldn't get it to compile.

**Comment by Savjee** [comment]
I tried compiling it from source and now it seems to work. Here is my binary (darwin_amd64): https://www.dropbox.com/s/p0ji13u73603i9h/apex_darwin_amd64?dl=0

Maybe someone could document the process of compiling Apex from source? I had a lot of issue's because I'm a noob with Go. Basically I ended up running "go get" countless of times to install the dependencies, but that's probably not the way to go.

**Comment by webjay** [comment]
Had the same problem, @Savjee's binary helped. Thx.

**Comment by jimlears** [comment]
the custom binary @Savjee dropped runs, but still having issues. is this being worked on?

**Comment by diranged** [comment]
:+1: .. this works. can we get this fixed on the official release?

**Comment by istrobes** [comment]
thx @Savjee, this is a working solution for now until we get an official release. 👌

**Comment by webnandroid** [comment]
Can any body tell me that how to configure apex on windows 7 32 bit. I try to configure it but its binary not executing

**Comment by febbraro** [comment]
I can also confirm the above issues and the binary provided be @Savjee works.

**Comment by febbraro** [comment]
Will we need to do another sierra rebuild for 0.11.0?

**Comment by tj** [comment]
Possibly yea, I have no reason to update to Sierra really, rather not gamble with things breaking

**Comment by febbraro** [comment]
Just to let folks know, I have been using the latest release on sierra for about a week now with none of the issues that I saw previously.
