### ISSUE TITLE
Python example is broken

### ISSUE THREAD

**Issue by clamorisse** [apex/apex#573]
If you have a bug report please let us know the following:

  - __Operating system__: Mac OSX (latest)
  - __Apex Version__: v0.10.3

When I run apex init and then apex deploy for python project, there was an error:
```
apex deploy
   • config unchanged          env= function=hello
   • code unchanged            env= function=hello
   • config unchanged          env= function=simple
   • code unchanged            env= function=simple
   ⨯ Error: function dependency: build hook: Collecting requests (from -r requirements.txt (line 1))
  Using cached requests-2.11.1-py2.py3-none-any.whl
Installing collected packages: requests
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

Could you point me in right direction?

**Comment by tj** [comment]
hmm maybe this fixes? https://github.com/apex/apex/commit/6b18fe465e02b3dda9ca76691e5a68917577642a, I'm not really familiar with python's tooling

**Comment by clamorisse** [comment]
It is an issue of homebrew and OS X, this [post](http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-bothurl) worked to solve the problem. Thanks.

**Comment by temoto** [comment]
In that link they recommend to create `~/.pydistutils.cfg` which helps with issue in question, but breaks further usage of pip outside apex build.

(So far most helpful) solution from Amazon is to create `functions/{name}/setup.cfg` with same content as in link before:

```
[install]
prefix=
```

It fixes pip install in apex build, but also doesn't break pip usage outside apex.

If apex would create this `setup.cfg` automatically (which is very weird), that'd work everywhere and could be a useful build hook enabled by default.

[1] https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html
