### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by gurre** [apex/apex#625]
- __Operating system__: Darwin 15.6.0
  - __Apex Version__: Apex version 0.11.0

Im spawning a process inside of a Go-program. The output from the program produces an error within Apex.

Perhaps making the JS-shim more robust?

```
SyntaxError: Unexpected token G
    at Object.parse (native)
    at LineStream.exports.handle.ctx (/var/task/index.js:35:18)
    at LineStream.emit (events.js:95:17)
    at LineStream.<anonymous> (_stream_readable.js:765:14)
    at LineStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at LineStream.Readable.push (_stream_readable.js:128:10)
    at LineStream.Transform.push (_stream_transform.js:140:32)
```

**Comment by mooyoul** [comment]
Note that [stdout of Go program is reserved for the shim](https://github.com/apex/go-apex#notes), and stdout of Go program should be print valid JSON. because [communication between shim and Go program uses JSON](https://github.com/apex/apex/blob/2d4b73f999184f82b4d42f842cea5ecbb570e812/shim/index.js#L35). 

Anyway, the reason why Node.js runtime throws error is Node.js runtime tried to parse `G (blabla)` text in JSON which is invalid JSON syntax. string values are will represented by wrapped double quotes.
For example, if you want to represent `foo` string in JSON, it should be `"foo"`, not `foo`.

so If you spawn process from (shimmed) Go program, you should not pipe stdout of spawned process to stdout of your Go program writes if that spawned process doesn't print JSON :)

**Comment by tj** [comment]
Yeah the shim doesn't necessarily have to be stdio, but it is for now, definitely have to avoid using stdout from the Go program (most loggers etc log to stderr anyway).
