### ISSUE TITLE
Can i Invoke lambda from another lambda with apex go-lang?

### ISSUE THREAD

**Issue by murali6** [apex/apex#677]
When lambda function call another go lambda that use apex wrapper,  i m getting  below error,

2017-02-14T19:04:33.920Z	6b185563-f2e8-11e6-8b76-15a655874da5	SyntaxError: Unexpected token /
at Object.parse (native)
at LineStream.<anonymous> (/var/task/index.js:35:18)
at emitOne (events.js:77:13)
at LineStream.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at LineStream.Readable.push (_stream_readable.js:110:10)
at LineStream.Transform.push (_stream_transform.js:127:32)
at LineStream._pushBuffer (/var/task/byline.js:123:17)
at LineStream._transform (/var/task/byline.js:114:8)
at LineStream.Transform._read (_stream_transform.js:166:10)

**Comment by murali6** [comment]
when i run locally as go service it's invoking lambda function, but if i invoke from lambda to another lambda its failing to invoke. Pls suggest

**Comment by tj** [comment]
Check out https://github.com/apex/invoke, that's wha I use for calling other Lambda functions in my Go stuff

**Comment by tj** [comment]
example is https://godoc.org/github.com/apex/invoke#example-package

**Comment by murali6** [comment]
perfect. This helps ... thanks tj
