### ISSUE TITLE
executing go in lambda fails

### ISSUE THREAD

**Issue by ecornelisse** [apex/apex#756]
OS: win10
Apex: 0.14.0

deploying my go function goes well but when i run it i get the following errors in cloudwatch. I have no clue on what is going wrong. Anyone here got some good ideas?

> module
 initialization error: Error at exports._errnoException (util.js:870:11) at ChildProcess.spawn (internal/child_process.js:298:11) at Object.exports.spawn (child_process.js:362:9) at Object.<anonymous> (/var/task/index.js:15:18) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Functio
module initialization error: Error
at exports._errnoException (util.js:870:11)
at ChildProcess.spawn (internal/child_process.js:298:11)
at Object.exports.spawn (child_process.js:362:9)
at Object.<anonymous> (/var/task/index.js:15:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

The deploy command outputs the following:

>  • loading functions in functions
   • open                      env= function=MyAppName
   • inferring runtime         env= function=MyAppName
   • inferred runtime          env= function=MyAppNameruntime=golang
   • deploying 1 functions
   • deploying                 env= function=MyAppName
   • building zip              env= function=MyAppName
   • creating build            env= function=MyAppName
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main *.go env= function=MyAppName hook=build
   • add shim                  env= function=MyAppName
   • add file to zip           env= file=main function=MyAppName
   • add file to zip           env= file=main.go function=MyAppName
   • created build (2.2 MB)    env= function=MyAppName
   • fetching config           env= function=MyAppName
   • config unchanged          env= function=MyAppName
   • code changed              env= function=MyAppName local=7+d3AWaUeRIKgXDWMTUkHWPtIrNHHOiLh6YKy1YiIYo= remote=A655KJDmXQLfWzBM6y/YcfLCTOkBNs4jJ2ie3HgX/R8=
   • updating function         env= function=MyAppName
   • updated alias current     env= function=MyAppName version=10
   • function updated          env= function=MyAppName name=MyAppName version=10
   • cleaning 1 functions
   • hook                      command=rm -f main env= function=MyAppName hook=clean
   • conditional flush         above_duration=24h0m0s above_size=500 age=1h47m17.7182726s size=88
   • close

**Comment by tj** [comment]
hmm I haven't seen this, sounds like it's maybe an intermittent AWS Lambda bug (https://github.com/serverless/serverless/issues/3176). Maybe try deleting it and re-deploying, or pushing a new version

**Comment by ecornelisse** [comment]
i did apex delete and apex deploy. Now cloudwatch shows

> module initialization error: Error at Module.require (module.js:353:17) at require (internal/module.js:12:17)
module initialization error: Error
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

Looks like the same as 3176

**Comment by tj** [comment]
did you manually specify a handler in project.json or function.json? I should add that to the log output, but that might be the issue

**Comment by ecornelisse** [comment]
No I don't have a function.json. my project.json is default and the same as Apex init created for me. Should I add a function.json? And what values do you advice?

**Comment by tj** [comment]
defaults there should be fine, I'm using the latest version with tons of Go functions though, not sure what that error would be, very vague error, and apex doesn't create a module.js

**Comment by chrisfentiman** [comment]
Apex init creates a javascript file, not a go file. If you don't set the runtime to "golang", it will throw an error like the one you have described and not work. It is very easy to do when using the `apex init` command.

Your project.json should look like this for example:
```
{
  "name": "cool_function",
  "description": "",
  "memory": 128,
  "timeout": 100,
  "runtime": "golang",
  "role": "somearnhere",
  "environment": {
  }
}
```

@tj Not sure if it was intended but the initial project.json doesn't define the field "runtime" when using `apex init`. I assume this is because the hello function is js.

**Comment by tj** [comment]
Ah yeah we have some inference to detect which language the function is using (based on `index.js`, `main.go`, etc)

**Comment by msteckyefantis** [comment]
I had a similar error to this, and the serverless issue using servleress. When I tested the function in the browser console I got a different EACCESS error, turned out to be related to [this](https://acloud.guru/forums/aws-lambda/discussion/-KSVv58PhKhA1c6a6EZ-/errormessage-eacces-permission-denied-open-vartaskcsvreadjs).

I recursively used chmod 777 and it worked. I don't know if this is the same issue you are having but it's worth a try 🐕.

**Comment by ibmboy19** [comment]
I'm sure that it occurs just in Windows platform!

**Comment by msteckyefantis** [comment]
@ibmboy19 Nah bruh, it happened on my Mac.

**Comment by ibmboy19** [comment]
msteckyefantis Thanks bruh... I hope someone could fix this soon...

**Comment by jonee** [comment]
simple example for working with Apex and Golang
https://github.com/jonee/apex_php_ruby/tree/master/mydomain.org/test/apextest/functions/sample_go

Maybe compare sample_go/function.json with what you have. The codes and scripts there should work.

**Comment by richardw679** [comment]
I've been experiencing the same problem on Windows.  It turns out that the zip that's created does not have the posix executable bit set on the golang executable.  By a tedious process of FTPing the zip to a Linux server, unzipping, chmodding a+x the 'main' file, re-zipping, and FTPing back to Windows I can successfully deploy and invoke the function.

**Comment by vishal8492** [comment]
I'm facing this on docker image. It works well with Mac Osx 10.13 . I'm using same apex version on both. 

Linux Kernel : Linux 68118f2d0c7b 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 Linux
OSX : Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Permission are same on both for build zip : -rw-r--r--
