### ISSUE TITLE
Support for adding lambda tags through json file

### ISSUE THREAD

**Issue by lucas-rudd** [apex/apex#790]
Currently apex does not support automatically adding or updating lambda tags read through the project.json file. I have added this support on a branch in my repo and would like to discuss this issue before opening a PR. Is there a reason this is not currently supported, and would this feature be desirable?

**Comment by tj** [comment]
I just haven't had a need for them personally, but I've seen an issue or two, happy to take a look at a pull-request!

**Comment by jonathanhughes** [comment]
We use tagging to categorize resources and schedule cleanup.  This would be a very useful feature for us.

**Comment by xoraes** [comment]
@tj what happened here? I see that this was merged but I don't see the changes for this on master. I'd like to use the tags support as I have a number of lambdas that need to be tagged based on company guidelines.

**Comment by lucas-rudd** [comment]
@tj @jonathanhughes we are using a custom build of apex in a docker container to deploy our lambdas with tags defined in config and have had absolutely no issues. We would be more than happy to work with you to address anything that may have prevented this from getting released. I can open another PR with the code we wrote if you're still interested in pushing this out.

**Comment by tj** [comment]
ah I think I had to revert it due to a panic or something, I forget, I should have left a comment

**Comment by xoraes** [comment]
@tj can we reopen this issue then?

**Comment by lucas-rudd** [comment]
@xoraes @tj I reopened a PR.

**Comment by ahmedrad** [comment]
Would love to see this feature as well!

**Comment by voigt** [comment]
Hey,

any news on this? At least some information about whats missing right now?
There is a [PR](https://github.com/apex/apex/pull/836) open for 9 months now...

**Comment by tj** [comment]
In this case probably just to test that with/without tags don't case any panic()s and that it works as advertised, definitely depends on the feature

**Comment by vigneshsenapathy** [comment]
@tj @voigt : any update on this. Wanted to know which version this change is going to be in

**Comment by voigt** [comment]
Hey,

most of the time the tagging worked fine. However, I ran into some issues with the feature from time to time.
I wanted to double check whether its actually the tagging or something on my side.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x141436c]

goroutine 7 [running]:
github.com/apex/apex/function.(*Function).tags(0xc42015ed00, 0xc4204aa520, 0x280e9f8)
	/Users/christophvoigt/go/src/github.com/apex/apex/function/function.go:934 +0x5c
github.com/apex/apex/function.(*Function).Create(0xc42015ed00, 0xc42040c000, 0x43e, 0xe00, 0xc4203fba40, 0x1)
	/Users/christophvoigt/go/src/github.com/apex/apex/function/function.go:415 +0xd5
github.com/apex/apex/function.(*Function).Deploy(0xc42015ed00, 0x178c758, 0xc42008e1e0)
	/Users/christophvoigt/go/src/github.com/apex/apex/function/function.go:248 +0x2dc
github.com/apex/apex/project.(*Project).Deploy.func1.1(0xc42008e1e0, 0xc42015ed00, 0xc42008e240)
	/Users/christophvoigt/go/src/github.com/apex/apex/project/project.go:205 +0x62
created by github.com/apex/apex/project.(*Project).Deploy.func1
	/Users/christophvoigt/go/src/github.com/apex/apex/project/project.go:202 +0x9e
	to retry, use: --limit @/Users/christophvoigt/go/src/github.com/[...]
```

What I can already say:

* creating tags works fine (on greenfield)
* adding/removing/adjusting seems to cause issues
